### ISSUE TITLE
[BUG]  Swag-Cloudflare-STUCK

### ISSUE THREAD

**Issue by digicloudgithub** [linuxserver/docker-swag#475] opened 2024-04-24 05:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

stuck with 

Please set the DNSPLUGIN variable to one of the following:

nothing else after

### Expected Behavior

run like normal

### Steps To Reproduce

open portainer run as a stack (tried by itself in the stack), use cloudflare as the dns plugin  (also tried godaddy had the same issue so then moved over to cloudflare because i seen people using it with success but the same issue)

### Environment

```markdown
- OS:
- How docker service was installed:
OMV6
Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100 
      - TZ=America/New_York
      - URL=************
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare

    volumes:
      - /srv/*****/****/swag:/config
    ports:
      - 443:443
      - 81:80

    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    100
───────────────────────────────────────
generating self-signed keys in /config/keys, you can replace these with your own keys if required
...+.+.........+++++++++++++++++++++++++++++++++++++++*......+.+++++++++++++++++++++++++++++++++++++++*.....+.+............+..............+...+.......+........+..................+...+....+...+...+..+....+...+..+...+......+....+.....+.+..........................+.+.....+..........+..............+.........+......+.+.........+...........+....+......+...+.....................+.....+...+.+......+...+.....+.............+...+..+............+.+...........+......+...+.+......+..+.+..+..........+..+......+.+.....+..........+.....+..........+...+..+....+.....+....+.....+.....................+....+...+............+...........+......+...+.+..+..........+.....+...+............+.......+......+......+...+.....+......................+...+...+........+.+.....+......+..................+.+...........+...+.......+..+..........+..+....+.....................+......+...+.....+......+.+........+.+...+........+.........+.+............+.....+.+.........+......+............+...+.........+...+..+......+.......+..+.+......+........+...+...+......+.+........+............+.......+.....+..........+......+.....+......+..........+........+.+......+...+.....+...+....+..............+......+..........+........+.+.....+.........+......+.+.............................++++++
...+++++++++++++++++++++++++++++++++++++++*.....+...........+....+...+...+........+.+......+........+.+.....+...+++++++++++++++++++++++++++++++++++++++*......+..............+.+......+........+.+......+......+...+...........+.........+....+........+.........+.+.....+............+.+.........+.....+......+......+........................+....+..+.+........+....+...+.....+.........+....+......+........+...+....+....................+.........+.+.....+.+.....+.......++++++
-----
Variables set:
PUID=1000
PGID=100
TZ=America/New_York
URL=**********
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=
STAGING=
Please set the DNSPLUGIN variable to one of the following:
```

**Comment by digicloudgithub** [comment] 2024-04-25 03:09
any help would be greatly appreciated

**Comment by digicloudgithub** [comment] 2024-04-25 11:22
AMD Phenom(tm) 9150e Quad-Core Processor. Open media vault, latest also running portainer

**Comment by Roxedus** [comment] 2024-04-25 12:06
Dupe of #469, your CPU is too old for tone of the requirements of certbot.

**Closed by Roxedus** 2024-04-25 12:06 UTC

**Comment by digicloudgithub** [comment] 2024-04-25 12:08
Even though it was working fine with duckdns for months ?

**Comment by Roxedus** [comment] 2024-04-25 12:09
Yes. its a recent change, as projects don't want to be limited by 15 year old hardware.

**Comment by digicloudgithub** [comment] 2024-04-25 12:12
How recent, because duckdns was working as of 2 days ago just fine. I can even revert back to it but I wanted to use my own domain name instead.
