### ISSUE TITLE
[BUG] 522 Error CloudFlare since Today

### ISSUE THREAD

**Issue by LinkinsRepeater** [linuxserver/docker-swag#418] opened 2023-10-04 17:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the latest update today my reverse proxy doesn't work anymore. I've not changed my configs in years and was working until now.
I've tried rolling back to a previous version but that doesn't work either.

I'm using cloudflare to reverse proxy via subdomains.
Checked duckdns, all my IP's are correct.

Is it possible something changed, or needs to changed? 

In the logs I've redacted out my domain and e-mail.

### Expected Behavior

Site just being accessible via reverse proxy.

### Steps To Reproduce

Use latest as of October 4.
Attempt to access any subdomain.

### Environment

```markdown
- OS: Unraid 6.12.4
- How docker service was installed: Via community apps (lscr.io/linuxserver/swag)
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='swag'
  --net='proxynet'
  -e TZ="Europe/Paris"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="swag"
  -e 'URL'='domain'
  -e 'VALIDATION'='dns'
  -e 'SUBDOMAINS'='wildcard'
  -e 'CERTPROVIDER'=''
  -e 'DNSPLUGIN'='cloudflare'
  -e 'PROPAGATION'=''
  -e 'DUCKDNSTOKEN'=''
  -e 'EMAIL'='e-mail'
  -e 'ONLY_SUBDOMAINS'='true'
  -e 'EXTRA_DOMAINS'=''
  -e 'STAGING'='false'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver-ls-logo.png'
  -p '1443:443/tcp'
  -p '180:80/tcp'
  -v '/mnt/user/appdata/swag':'/config':'rw'
  --cap-add=NET_ADMIN 'lscr.io/linuxserver/swag'
99c3538457c6c0c32f604dc05fa89338ad15713531f5dc89145e0b9eeb4869b6

The command finished successfully!
```

### Container logs

```bash
text  error  warn  system  array  login  

[ls.io-init] done.
Server ready
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Variables set:
PUID=99
PGID=100
TZ=Europe/Paris
URL=[DOMAIN]
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=true
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=[MY E-MAIL]
STAGING=false

Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for linkinsrepeater.com will be requested
E-mail address entered: [MY E-MAIL]
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
/config/nginx/ldap.conf exists.
        Please apply any customizations to /config/nginx/ldap-server.conf
        Ensure your configs are updated and remove /config/nginx/ldap.conf
        If you do not use this config, simply remove it.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-05-28 │ 2023-04-27 │ /config/nginx/authelia-server.conf                                     │
│ 2023-02-05 │ 2023-05-31 │ /config/nginx/proxy-confs/wizarr.subdomain.conf                        │
│ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/sonarr.subdomain.conf                        │
│ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/plex.subdomain.conf                          │
│ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/thelounge.subdomain.conf                     │
│ 2022-09-08 │ 2023-05-31 │ /config/nginx/proxy-confs/prowlarr.subdomain.conf                      │
│ 2022-09-08 │ 2023-05-31 │ /config/nginx/proxy-confs/privatebin.subdomain.conf                    │
│ 2022-09-08 │ 2023-05-31 │ /config/nginx/proxy-confs/bazarr.subdomain.conf                        │
│ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/radarr.subdomain.conf                        │
│ 2021-05-18 │ 2023-05-31 │ /config/nginx/proxy-confs/qbittorrent.subdomain.conf                   │
│ 2022-09-08 │ 2023-05-31 │ /config/nginx/proxy-confs/vaultwarden.subdomain.conf                   │
│ 2022-09-08 │ 2023-05-31 │ /config/nginx/proxy-confs/overseerr.subdomain.conf                     │
│ 2021-05-18 │ 2023-06-24 │ /config/nginx/proxy-confs/nextcloud.subdomain.conf                     │
│ 2022-01-09 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2021-10-26 │ 2023-02-09 │ /config/nginx/proxy.conf                                               │
│ 2023-02-09 │ 2023-04-27 │ /config/nginx/authentik-server.conf                                    │
│ 2020-06-02 │ 2022-08-20 │ /config/nginx/ldap-server.conf                                         │
│ 2021-04-27 │ 2023-06-05 │ /config/nginx/site-confs/default.conf                                  │
│ 2021-09-19 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│ 2021-04-21 │ 2023-04-27 │ /config/nginx/authelia-location.conf                                   │
│ 2023-02-09 │ 2023-04-27 │ /config/nginx/authentik-location.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Server ready
```

**Comment by aptalca** [comment] 2023-10-04 17:21
1. Your confs are super old, you need to update them
2. 522 is a cloudflare proxy error, not something we provide support for

Closing as it's not a bug. You can seek support on our discord or discourse (without cloudflare proxy)

**Closed by aptalca** 2023-10-04 17:21 UTC
