### ISSUE TITLE
Wordpress.subdomain.conf.sample

### ISSUE THREAD

**Issue by mjeshurun** [linuxserver/docker-swag#285] opened 2022-10-22 14:55 UTC
Hi friends, 
I would like to migrate my wordpress website from Namecheap hosting to my new home server, and have the website run behind nginx using swag as a reverse proxy. 
In my swag docker folder I can not find a sample for the wordpress.subdomain.conf file. the only configuration file sample i see for wordpress is for the wordpress.subfolder.conf.
Can anyone share the correct subdomain.conf file or commands so I can create a correct wordpress.subdomain.conf file?
Hope someone can help 🙏

**Comment by aptalca** [comment] 2022-10-22 15:08
You can host wordpress directly in SWAG. See here: https://docs.linuxserver.io/general/swag#hosting-a-wordpress-site

Closing because it's not a bug

**Closed by aptalca** 2022-10-22 15:08 UTC
