### ISSUE TITLE
[BUG] Dashboard - Cleaning up resources...

### ISSUE THREAD

**Issue by df911** [linuxserver/docker-swag#456] opened 2024-02-06 08:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I enabled the swag-dashboard mods and I get this message when I try to connect to the dashboard : 
Cleaning up resources...

### Expected Behavior

Access to Dashboard KPI

### Steps To Reproduce

In docker file : ` DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard`

### Environment

```markdown
- OS: Openmediavault 
- How docker service was installed: Docker
```

### CPU architecture

x86-64

### Docker creation

```bash
DOCKER_MODS=linuxserver/mods:swag-maxmind|linuxserver/mods:swag-dashboard
```

### Container logs

```bash
**** Applying the SWAG dashboard mod... ****
libmaxminddb
**** goaccess already installed, skipping ****
**** libmaxminddb already installed, skipping ****
**** libmaxminddb already installed, skipping ****
**** The swag-dashboard conf has been updated ****
**** Compare the changes using the sample file: /config/nginx/proxy-confs/dashboard.subdomain.conf.sample
**** Applied the SWAG dashboard mod ****
Applying the maxmind mod...
Applied the maxmind mod
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Server ready
```

**Comment by drizuid** [comment] 2024-03-06 12:30
Have you changed the log format in swag?

**Comment by drizuid** [comment] 2024-03-06 14:54
dupe of https://github.com/linuxserver/docker-mods/issues/830

**Closed by drizuid** 2024-03-06 14:54 UTC
