### ISSUE TITLE
“stream” directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

### ISSUE THREAD

**Issue by Docttor** [linuxserver/docker-swag#322] opened 2023-01-22 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since the last update (2.2.0) I am geeting an error in my swag container, saying the following:

**nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3**

Running on UNRAID. Interessting is, that Inside the container I dont have “stream.conf” file. Also in user config there is no such “stream.conf” file. Before the latest update  everything was working without any issues.

With this error SWAG is not working for me.

Any help is appreciated.

### Steps To Reproduce

Update SWAG to the latest version 2.2.0 on UNRAID.

### Environment

```markdown
- OS: UNRAID
- How docker service was installed: UNRAID Apps
- was working without issues unless the latest update
```

### CPU architecture

x86-64

### Docker creation

```bash
Created from the "UNRAID Apps"
```

### Container logs

```bash
2. 01. 2023 18:31:19
Server ready
22. 01. 2023 18:31:20
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
22. 01. 2023 18:31:21
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
......
```

**Comment by Roxedus** [comment] 2023-01-22 17:35
Dupe of https://github.com/linuxserver/docker-swag/issues/321 https://github.com/linuxserver/docker-swag/issues/320 https://github.com/linuxserver/docker-swag/issues/319 https://github.com/linuxserver/docker-swag/issues/318 https://github.com/linuxserver/docker-swag/issues/316

**Closed by Roxedus** 2023-01-22 17:35 UTC

**Comment by Cyboc** [comment] 2023-01-22 17:53
My apologies, I didn't look at the closed issues
