### ISSUE TITLE
Reverse Proxy config

### ISSUE THREAD

**Issue by vic1707** [linuxserver/docker-swag#78] opened 2021-02-08 18:20 UTC
Hello, 

I'm looking for a way to use Swag as a reverse proxy for a wireguard server in order to be able to close the 51820 port on my router.

for now the `terminaison point is : wireguard.MYDOMAIN.EXT:51820`

My wireguard is running thanks to the 'WireHole' repo (in order to have pihole and unbound connected.

The Wireguard and Swag containers are both in the same docker network (as well as some of my others applications), wireguard is connected to another network as well (the one shared with pihole and unbound).

I'm struggling as how should my `wireguard.subdomain.conf` be (don't know anything about nginx)...

For now I tried this : 
```
server {
    listen 51820;
    listen [::]:51820;

    server_name wireguard.*;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app wireguard;
        set $upstream_port 51820;
        proxy_pass $upstream_app:$upstream_port;
    }
}
```

Thanks for helping !

**Comment by aptalca** [comment] 2021-02-08 18:31
That config is for http traffic so it won't work. Wireguard uses udp, which is not easily reverse proxied, but you can look into the nginx stream plugin, which is for proxying tcp (and udp) connections.

In any case, closing this as it is not a bug. Feel free to drop by our discord or discourse for more info.

**Closed by aptalca** 2021-02-08 18:31 UTC

**Comment by vic1707** [comment] 2021-02-11 10:00
Thanks for the advice, for now i'm struck with an `nginx: [emerg] "stream" directive is not allowed here in /config/nginx/proxy-confs/wireguard.subdomain.conf:1` error. will try to figure it out on my own before dropping to your discord ^^
