### ISSUE TITLE
ERROR: Cert does not exist (The DNS query name does not exist)

### ISSUE THREAD

**Issue by t-zxvf** [linuxserver/docker-swag#292] opened 2022-11-11 14:25 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Getting a certificate for the target Domain once deploying the image trough Docker Compose using VALIDATION=dns, via duckdns validation with a wildcard cert. 

## Current Behavior

Once deploying the image trough Docker Compose, everything seems to be ok but actually swag cannot receive certificate. 
## Steps to Reproduce

1. Create a new YML file for docker-compose 
2. Deploy the container via duckdns validation with a wildcard cert. 
3. Check  the logs with docker logs -f <container-name> 

## Environment
**OS:** Ubuntu Server 22.04.1 LTS
**CPU architecture:**  arm64 (Raspberry Pi 4 8GB)
**How docker service was installed:** officiale docker repo ->  linuxserver/swag:latest

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=mydomain.duckdns.org
      - VALIDATION=duckdns
      - SUBDOMAINS=wildcard
     - DUCKDNSTOKEN=token duckdns
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped
## Docker logs

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
Setting resolver to  127.0.0.11
Setting worker_processes to 4
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...............................................+++++
.................................................+++++
writing new private key to '/config/keys/cert.key'
-----
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/30-test-run
cont-init: info: /etc/cont-init.d/30-test-run exited 0
cont-init: info: running /etc/cont-init.d/31-require-url
cont-init: info: /etc/cont-init.d/31-require-url exited 0
cont-init: info: running /etc/cont-init.d/40-folders
cont-init: info: /etc/cont-init.d/40-folders exited 0
cont-init: info: running /etc/cont-init.d/41-samples
cont-init: info: /etc/cont-init.d/41-samples exited 0
cont-init: info: running /etc/cont-init.d/42-fail2ban
cont-init: info: /etc/cont-init.d/42-fail2ban exited 0
cont-init: info: running /etc/cont-init.d/43-crontabs
cont-init: info: /etc/cont-init.d/43-crontabs exited 0
cont-init: info: running /etc/cont-init.d/45-nginx
cont-init: info: /etc/cont-init.d/45-nginx exited 0
cont-init: info: running /etc/cont-init.d/50-certbot
Variables set:
PUID=1000
PGID=1000
TZ=Europe/Rome
URL=mydomain.duckdns.org
SUBDOMAINS=wildcard
EXTRA_DOMAINS=
ONLY_SUBDOMAINS=false
VALIDATION=duckdns
CERTPROVIDER=
DNSPLUGIN=
EMAIL=
STAGING=

Created .donoteditthisfile.conf
the resulting certificate will only cover the subdomains due to a limitation of duckdns, so it is advised to set the root location to use www.subdomain.duckdns.org
Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
Wildcard cert for only the subdomains of serverfdt.duckdns.org will be requested
No e-mail address entered or address invalid
dns validation via duckdns plugin is selected
Different validation parameters entered than what was used before. Revoking and deleting existing certificate, and an updated one will be created
Generating new certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for *.serverfdt.duckdns.org
Unsafe permissions on credentials configuration file: /config/dns-conf/duckdns.ini
Unsafe permissions on credentials configuration file: /config/dns-conf/duckdns.ini
The DNS query name does not exist: serverfdt.duckdns.org.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/duckdns.ini file.

**Comment by nemchik** [comment] 2022-11-11 15:14
This looks like a possible duplicate of https://github.com/linuxserver/docker-swag/issues/281
The issue discussed related to having a local DNS record for the duckdns subdomain, which causes the duckdns plugin to misbehave. This can be solved by adding a local DNS TXT record for the duckdns subdomain, or removing the local DNS record. If this is not the issue, we can look into what else could be happening.

**Comment by t-zxvf** [comment] 2022-11-11 16:22
Yess, you are right. I have the same issue and apparently, I solved adding "/etc/letsencrypt# mkdir -pv live/mydomain.com" as I read inside of #281. I don't know why but I can consider this issue solved.

**Comment by nemchik** [comment] 2022-11-13 23:31
Please try running `lspipepr/swag:1.32.0-pkg-96e270ce-pr-293`, it should work with local DNS records.

You may need to delete your `/config/keys` and `/config/etc` folders for swag.

Ref: https://github.com/linuxserver/docker-swag/pull/293

**Comment by t-zxvf** [comment] 2022-11-14 09:43
Thanks, it works finally. I can consider this issue solved.

**Closed** 2022-11-14 15:36 UTC
