### ISSUE TITLE
Checking nginx config results in failure due to nginx.pid in wrong place

### ISSUE THREAD

**Issue by liquid667** [linuxserver/docker-swag#110] opened 2021-04-13 08:18 UTC
It is not possible to do nginx commands properly due to the pid file being in the wrong place.

To reproduce run:
$> docker exec -ti <container-name> nginx -t
This produces that the /run/ngnix.pid is wrong and instead it is expected /run/nginx/nginx.pid

In my case i changed the default nginx.conf to /run/nginx/nginx.pid and changed the Dockerfile
to create the /run/nginx directory.

**Comment by Roxedus** [comment] 2021-04-13 08:25
Duplicate of #57

**Closed by Roxedus** 2021-04-13 08:25 UTC
