### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cyboc** [linuxserver/docker-swag#323] opened 2023-01-22 17:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After pulling the latest image version, the docker container log repeats continuously the message `nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3` and is not able to route any requests.

### Expected Behavior

The container starts as usual. It works with the image tag `:1.32.0-ls171`

### Steps To Reproduce

Execute swag container with previously working configuration with one of the following docker tags: `latest`, `2.2.0`, `1.32.0`

### Environment

```markdown
- OS: Debian 11
- How docker service was installed: according to instructions on docs.docker.com
```

### CPU architecture

x86-64

### Docker creation

```bash
swag:
    container_name: swag
    image: lscr.io/linuxserver/swag
    restart: ${RESTART_POLICY}
    ports:
      - $HTTPS_PORT:443
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - EMAIL=$MAIL
      - URL="my.domain" # necessary, since wildcard in this field leads to error
      - ONLY_SUBDOMAINS=false
      - DNSPLUGIN=cloudflare
      - VALIDATION=dns
      - EXTRA_DOMAINS="*.my.domain"
      - STAGING=false
    volumes:
      - ${CONFIG}:/config
      - $MEDIA:/media
    networks:
      - mynet
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
Certbot: https://supporters.eff.org/donate/support-work-on-certbot
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    xx
User gid:    xx
-------------------------------------
using keys found in /config/keys
Variables set:
PUID=xx
PGID=xx
TZ=
URL="my.domain"
SUBDOMAINS=
EXTRA_DOMAINS="*.my.domain"
ONLY_SUBDOMAINS=false
VALIDATION=dns
CERTPROVIDER=
DNSPLUGIN=cloudflare
EMAIL=xxxxxxxxxxx
STAGING=false
Using Let's Encrypt as the cert provider
No subdomains defined
EXTRA_DOMAINS entered, processing
Extra domains processed are:  -d *.my.domain 
E-mail address entered: xxxxxxxxxxxx
dns validation via cloudflare plugin is selected
Certificate exists; parameters unchanged; starting nginx
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
/config/nginx/geoip2.conf exists.
        Please migrate to https://github.com/linuxserver/docker-mods/tree/swag-maxmind
/config/nginx/ldap.conf exists.
        Please apply any customizations to /config/nginx/ldap-server.conf
        Ensure your configs are updated and remove /config/nginx/ldap.conf
        If you do not use this config, simply remove it.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
/config/nginx/proxy.conf
/config/nginx/ldap-server.conf
/config/nginx/nginx.conf
/config/nginx/ssl.conf

[.........................................]

[custom-init] No custom files found, skipping...
[ls.io-init] done.
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
2023-01-22 17:42:05,772 fail2ban.configreader   [357]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Server ready
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
...
```

**Comment by Roxedus** [comment] 2023-01-22 17:51
Dupe of https://github.com/linuxserver/docker-swag/issues/322 https://github.com/linuxserver/docker-swag/issues/321 https://github.com/linuxserver/docker-swag/issues/320 https://github.com/linuxserver/docker-swag/issues/319 https://github.com/linuxserver/docker-swag/issues/318 https://github.com/linuxserver/docker-swag/issues/316

**Closed by Roxedus** 2023-01-22 17:51 UTC
