### ISSUE TITLE
[BUG] [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

### ISSUE THREAD

**Issue by markisoke** [linuxserver/docker-swag#320] opened 2023-01-22 10:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After update [1.32.0-ls173](https://github.com/linuxserver/docker-swag/releases/tag/1.32.0-ls173) last night I've been thrown the following error in the logs: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3

This results in my swag container not starting.

### Steps To Reproduce

I'm using [2.2.0-ls174](https://github.com/linuxserver/docker-swag/releases/tag/2.2.0-ls174) now and it's still behaving the same

### Environment

```markdown
- OS: Ubuntu 18.04.6
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
Docker Compose:

# SWAG – SWAG including Nginx and PHP
  swag:
    image: "linuxserver/swag"
    hostname: swag
    container_name: "swag"
    volumes:
      - /opt/docker/swag/config:/config
    ports:
      - 443:443
      # Only for validation, redirect all http traffic to https in config
      - 80:80
    restart: always
    environment:
      - PUID=***
      - PGID=***
      - TZ=***
      - EMAIL=***
      - URL=***
      - EXTRA_DOMAINS=***
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    networks:
     swag:
       ipv4_address: 192.168.1.2
```

### Container logs

```bash
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/stream.conf:3
```

**Comment by markisoke** [comment] 2023-01-22 10:13
Reverting back to linuxserver/swag:1.32.0-ls172 solves the issue

**Comment by Roxedus** [comment] 2023-01-22 10:16
You claimed to have searched for other issues, yet this is a dupe of #319 #318 #316.

**Closed by Roxedus** 2023-01-22 10:16 UTC
