### ISSUE TITLE
Upgrade nginx to 1.19.4 or later

### ISSUE THREAD

**Issue by dsm1212** [linuxserver/docker-swag#131] opened 2021-06-02 14:01 UTC
I'd like to take advantage  of this: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake

When using a wildcard certificate I'd like to use that domain in my windows system configuration, but once set it is hit for all kinds of random names short names and those frequently come back with certificate mis-matches because the short name was responded to by nginx. WIth this update in 1.19.4 one can reject ssl requests when the host name is not a virtual server. The system looks like it is not there for invalid cnames.

My current swag has nginx 1.18 in it. There is an alternative method to achieve this on 1.18 but this patch is required: https://git.hakase.app/Hakase/openssl-patch

**Comment by Roxedus** [comment] 2021-06-02 14:03
Dupe of #125

**Closed by Roxedus** 2021-06-02 14:03 UTC

**Comment by dsm1212** [comment] 2021-06-02 14:11
Ah sorry, I searched open issues and didn't find it. I'll jump to the alpine site
